@echo off

echo 1- Transformations Started...
python transformDisasters.py 2>nul
echo DFDisasters Done...
python transformAgricultura.py 2>nul
echo DFAgricultura Done...
python transformDesempregados.py 2>nul
echo DFDesempregados Done...
python transformGDP.py 2>nul
echo DFGDP Done...
python transformPopulacao.py 2>nul
echo DFPopulacao Done...
python transformTurismo.py 2>nul
echo DFTurismo Done...
echo Transformations Completed!
echo.

echo 2- Dimensions Started...
python dimData.py 2>nul
echo DimData Done...
python dimEvent.py 2>nul
echo DimEvent Done...
python dimLocation.py 2>nul
echo DimLocation Done...
python dimType.py 2>nul
echo DimType Done...
python factDisaster.py 2>nul
echo DimDisaster Done...
echo Dimensions Created Completed!
echo.

echo 3- Load Started...
python loadData.py 2>nul
echo DimData Loaded...
python loadEvent.py 2>nul
echo DimEvent Loaded...
python loadLocation.py 2>nul
echo DimLocation Loaded...
python loadType.py 2>nul
echo DimType Loaded...
python loadDisaster.py 2>nul
echo FactDisaster Loaded...
echo Load Completed!
